spring:
  datasource:
    username: ${HYPERPROF_DB_USER}
    password: ${HYPERPROF_DB_PASSWORD}
    url: jdbc:h2:mem:${HYPERPROF_DB_NAME}
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    database-plataform: org.hibernate.dialect.H2Dialect
    properties:
      "hibernate.format_sql": false
  h2:
    console:
      enabled: true
      path: /h2-console