spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/hyperprof?useSSL=false&serverTimezone=America/Manaus
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true